create or replace task DEV_FACETS.FACETS_CORE_WORK.TASK_FID_IHT_DOWNCODE_GP_REPLICATE_ARCH
               warehouse=FACETS_INTEGRATION1_WH2
               after DEV_FACETS.FACETS_CORE_WORK.PARENT_TASK_2
               as
MERGE INTO FACETS_CORE_TARGET.FID_IHT_DOWNCODE_GP_REPLICATE_ARCH AS target
    USING
    (
    SELECT * FROM STREAM_FID_IHT_DOWNCODE_GP_REPLICATE_ARCH
    QUALIFY ROW_NUMBER() OVER(PARTITION BY LINE_SEQ, ICM_PRODUCT, CLAIM_ID, CREATE_DTM ORDER BY SOURCE_UPDATE_TMSTP DESC)=1
    ) AS source
    ON EQUAL_NULL(target.LINE_SEQ, source.LINE_SEQ) AND EQUAL_NULL(target.ICM_PRODUCT, source.ICM_PRODUCT) AND EQUAL_NULL(target.CLAIM_ID, source.CLAIM_ID) AND EQUAL_NULL(target.CREATE_DTM, source.CREATE_DTM) AND target.DELETED_IND = 'N'
    WHEN MATCHED AND METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = 'FALSE' THEN
        UPDATE SET target.DELETED_IND = 'Y', target.UPDATE_TMSTP = CURRENT_TIMESTAMP
    WHEN MATCHED AND METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = 'TRUE' THEN
        UPDATE SET target.REC_LINE_STATUS = source.REC_LINE_STATUS, target.REC_HCPCS = source.REC_HCPCS, target.CREATE_DTM = source.CREATE_DTM, target.LOAD_DATE = source.LOAD_DATE, target.SUB_HCPCS = source.SUB_HCPCS, target.REASON1_ID = source.REASON1_ID, target.SOURCE_UPDATE_TMSTP = source.SOURCE_UPDATE_TMSTP, target.UPDATE_TMSTP = CURRENT_TIMESTAMP , target.DELETED_IND = 'N', target.PROCEDURE_REC_FLAG = source.PROCEDURE_REC_FLAG , target.MODIFIER_REC_FLAG = source.MODIFIER_REC_FLAG
    WHEN MATCHED AND METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = 'FALSE' THEN
        UPDATE SET target.REC_LINE_STATUS = source.REC_LINE_STATUS, target.REC_HCPCS = source.REC_HCPCS, target.CREATE_DTM = source.CREATE_DTM, target.LOAD_DATE = source.LOAD_DATE, target.SUB_HCPCS = source.SUB_HCPCS, target.REASON1_ID = source.REASON1_ID, target.SOURCE_UPDATE_TMSTP = source.SOURCE_UPDATE_TMSTP, target.UPDATE_TMSTP = CURRENT_TIMESTAMP , target.DELETED_IND = 'N', target.PROCEDURE_REC_FLAG = source.PROCEDURE_REC_FLAG , target.MODIFIER_REC_FLAG = source.MODIFIER_REC_FLAG
    WHEN NOT MATCHED THEN
        INSERT (REC_LINE_STATUS, CLAIM_ID, LINE_SEQ, REC_HCPCS, ICM_PRODUCT, CREATE_DTM, LOAD_DATE, SUB_HCPCS, REASON1_ID, SOURCE_UPDATE_TMSTP, SOURCE_INSERT_TMSTP ,SOURCE_SYSTEM_CODE, INSERT_TMSTP, UPDATE_TMSTP, PROCEDURE_REC_FLAG, MODIFIER_REC_FLAG)
        VALUES (source.REC_LINE_STATUS, source.CLAIM_ID, source.LINE_SEQ, source.REC_HCPCS, source.ICM_PRODUCT, source.CREATE_DTM, source.LOAD_DATE, source.SUB_HCPCS, source.REASON1_ID, source.SOURCE_UPDATE_TMSTP, source.SOURCE_UPDATE_TMSTP, 'FID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, source.PROCEDURE_REC_FLAG, source.MODIFIER_REC_FLAG)
