-- ============================================
-- Step 5: Verify Data is Flowing into Snowflake
-- ============================================

-- Check row counts across all 3 tables
SELECT 'WEATHER_RAW_DATA' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
    FROM WEATHER_PIPELINE.KAFKA_DATA.WEATHER_RAW_DATA
UNION ALL
SELECT 'WEATHER_PREDICTIONS', COUNT(*)
    FROM WEATHER_PIPELINE.KAFKA_DATA.WEATHER_PREDICTIONS
UNION ALL
SELECT 'WEATHER_ALERTS', COUNT(*)
    FROM WEATHER_PIPELINE.KAFKA_DATA.WEATHER_ALERTS;

-- Latest 5 raw readings
SELECT CITY, TIMESTAMP, TEMPERATURE_C, HUMIDITY_PCT, WIND_SPEED_KMH
FROM WEATHER_PIPELINE.KAFKA_DATA.WEATHER_RAW_DATA
ORDER BY TIMESTAMP DESC LIMIT 5;

-- Latest prediction for Mumbai (flatten nested array)
SELECT CITY, GENERATED_AT,
    f.value:date::STRING AS forecast_date,
    f.value:temp_high_c::FLOAT AS high_temp,
    f.value:temp_low_c::FLOAT AS low_temp,
    f.value:condition::STRING AS condition,
    f.value:confidence_pct::FLOAT AS confidence
FROM WEATHER_PIPELINE.KAFKA_DATA.WEATHER_PREDICTIONS,
    LATERAL FLATTEN(input => PREDICTIONS) f
WHERE CITY = 'Mumbai'
ORDER BY GENERATED_AT DESC, f.index LIMIT 7;

-- All HIGH severity alerts
SELECT CITY, TIMESTAMP, SEVERITY, ALERT_TYPE, ACTUAL_VALUE, THRESHOLD, MESSAGE
FROM WEATHER_PIPELINE.KAFKA_DATA.WEATHER_ALERTS
WHERE SEVERITY = 'HIGH'
ORDER BY TIMESTAMP DESC LIMIT 10;

-- Monitor ingestion latency
SELECT
    MAX(TIMESTAMP) AS LATEST_RECORD,
    CURRENT_TIMESTAMP() AS CURRENT_TIME,
    DATEDIFF('second', MAX(TIMESTAMP), CURRENT_TIMESTAMP()) AS LAG_SECONDS
FROM WEATHER_PIPELINE.KAFKA_DATA.WEATHER_RAW_DATA;
